module.exports = 
{
  "data":{
     "*profile":"urn:li:fs_profile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "summaryTreasuryMediaCount":1,
     "*summaryTreasuryMedias":[
        "urn:li:fs_treasuryMedia:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1549210628533)"
     ],
     "*patentView":"urn:li:fs_patentView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*honorView":"urn:li:fs_honorView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*educationView":"urn:li:fs_educationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*volunteerExperienceView":"urn:li:fs_volunteerExperienceView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*volunteerCauseView":"urn:li:fs_volunteerCauseView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "$type":"com.linkedin.voyager.identity.profile.ProfileView",
     "*testScoreView":"urn:li:fs_testScoreView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*skillView":"urn:li:fs_skillView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "$deletedFields":[
        "entityLocale"
     ],
     "*projectView":"urn:li:fs_projectView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "entityUrn":"urn:li:fs_profileView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*certificationView":"urn:li:fs_certificationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*languageView":"urn:li:fs_languageView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*courseView":"urn:li:fs_courseView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*publicationView":"urn:li:fs_publicationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*positionGroupView":"urn:li:fs_positionGroupView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "primaryLocale":{
        "country":"US",
        "language":"en",
        "$type":"com.linkedin.common.Locale"
     },
     "*organizationView":"urn:li:fs_organizationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
     "*positionView":"urn:li:fs_positionView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M"
  },
  "included":[
    {  
      "$deletedFields":[  
         "universalName"
      ],
      "objectUrn":"urn:li:company:1062",
      "entityUrn":"urn:li:fs_miniCompany:1062",
      "name":"Sun Microsystems",
      "showcase":false,
      "active":true,
      "logo":{  
         "artifacts":[  
            {  
               "width":200,
               "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=CZ9oNah4dROysHQpubw7VZD84fBbHPFZgkxluAVW9oo",
               "expiresAt":1557964800000,
               "height":200,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":100,
               "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=o0RCvscQO93N28xQN2C4mRF7vFnUoCZB59QuHFsCBR0",
               "expiresAt":1557964800000,
               "height":100,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":400,
               "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=q35pNQIQCV0GDv5YWGJ6b6Avg4D8m7FW1UhqK6FslyU",
               "expiresAt":1557964800000,
               "height":400,
               "$type":"com.linkedin.common.VectorArtifact"
            }
         ],
         "rootUrl":"https://media.licdn.com/dms/image/C4D0BAQG8U0EaYqTApg/company-logo_",
         "$type":"com.linkedin.common.VectorImage"
      },
      "trackingId":"Jbxk/zD9TyCjExOhHYrOGg==",
      "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
   },
   {  
      "$deletedFields":[  
         "universalName"
      ],
      "objectUrn":"urn:li:company:5738",
      "entityUrn":"urn:li:fs_miniCompany:5738",
      "name":"The University of Edinburgh",
      "showcase":false,
      "active":true,
      "logo":{  
         "artifacts":[  
            {  
               "width":200,
               "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=Sl3kEyzyO9ef0sqZtOEyca_hAZ2lZx7K8uXifwJqe54",
               "expiresAt":1557964800000,
               "height":200,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":100,
               "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=UtjjKjm9auHnM_fBakNlp59OZmWCr3HPRAmenEw0lMQ",
               "expiresAt":1557964800000,
               "height":100,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":400,
               "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=8l2mSYVK7M7c3hwxxdyTosxctjG0VQOBGHAP5oxgSLc",
               "expiresAt":1557964800000,
               "height":400,
               "$type":"com.linkedin.common.VectorArtifact"
            }
         ],
         "rootUrl":"https://media.licdn.com/dms/image/C4D0BAQFSi1nlisxTcg/company-logo_",
         "$type":"com.linkedin.common.VectorImage"
      },
      "trackingId":"uE3bgMbVSkaQ0yOPkTrphw==",
      "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
   },
   {  
      "$deletedFields":[  
         "universalName"
      ],
      "objectUrn":"urn:li:company:1586",
      "entityUrn":"urn:li:fs_miniCompany:1586",
      "name":"Amazon",
      "showcase":false,
      "active":true,
      "logo":{  
         "artifacts":[  
            {  
               "width":200,
               "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=o8V9YIiRX9HtEzjdi2m1Ly-fsOfCRsD7kQ1QfYT3Isk",
               "expiresAt":1557964800000,
               "height":200,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":100,
               "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=d3RY2JWTBy8J1nF_NnZa3Cw6PV2jalYwNcTtbK1G_U0",
               "expiresAt":1557964800000,
               "height":100,
               "$type":"com.linkedin.common.VectorArtifact"
            },
            {  
               "width":400,
               "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=ENfbrPm5NqhVBwYcc22TQjdydNJoTay55Znnvy9h4xA",
               "expiresAt":1557964800000,
               "height":400,
               "$type":"com.linkedin.common.VectorArtifact"
            }
         ],
         "rootUrl":"https://media.licdn.com/dms/image/C4D0BAQHi-82ItMq_9g/company-logo_",
         "$type":"com.linkedin.common.VectorImage"
      },
      "trackingId":"dzdGQz4vSSmjtWqQnA76sQ==",
      "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
   },
   {  
      "$deletedFields":[  
         "courses",
         "projects",
         "honors",
         "entityLocale",
         "organizations",
         "promotion"
      ],
      "locationName":"Edinburgh, United Kingdom",
      "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,47250208)",
      "companyName":"The University of Edinburgh",
      "timePeriod":{  
         "endDate":{  
            "month":10,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":6,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "description":"Implementation of my thesis \"Evolving a Neural Model of Insect Path Integration\" on a physical robot and publication in the journal \"Adaptive Behavior\".\n\nhttp://journals.sagepub.com/doi/abs/10.1177/1059712307082080",
      "company":{  
         "employeeCountRange":{  
            "start":5001,
            "end":10000,
            "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
         },
         "industries":[  
            "Research"
         ],
         "*miniCompany":"urn:li:fs_miniCompany:5738",
         "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
      },
      "title":"Research and publication of my bachelor thesis ",
      "region":"urn:li:fs_region:(gb,4574)",
      "companyUrn":"urn:li:fs_miniCompany:5738",
      "recommendations":[  

      ],
      "$type":"com.linkedin.voyager.identity.profile.Position"
   },
   {  
      "$deletedFields":[  
         "courses",
         "projects",
         "description",
         "companyUrn",
         "honors",
         "entityLocale",
         "organizations",
         "company",
         "promotion"
      ],
      "locationName":"Edinburgh, United Kingdom",
      "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295173992)",
      "companyName":"Edinburgh Pedicabs",
      "timePeriod":{  
         "endDate":{  
            "month":1,
            "year":2005,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":1,
            "year":2003,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "title":"Pedicabbing (riding a cycle­taxi) in Edinburgh to help fund degree.",
      "region":"urn:li:fs_region:(gb,4574)",
      "recommendations":[  

      ],
      "$type":"com.linkedin.voyager.identity.profile.Position"
   },
   {  
      "$deletedFields":[  
         "courses",
         "projects",
         "honors",
         "entityLocale",
         "organizations",
         "promotion"
      ],
      "locationName":"Edinburgh, United Kingdom",
      "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295173319)",
      "companyName":"Amazon",
      "timePeriod":{  
         "endDate":{  
            "month":2,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":10,
            "year":2006,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "description":"Agile development of backend tooling. A/b testing of data mining technologies for sales optimization.\n\nTech: java × spring framework × test driven development × agile development × python × distributed computing",
      "company":{  
         "employeeCountRange":{  
            "start":10001,
            "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
         },
         "industries":[  
            "Internet"
         ],
         "*miniCompany":"urn:li:fs_miniCompany:1586",
         "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
      },
      "title":"Software Engineer",
      "region":"urn:li:fs_region:(gb,4574)",
      "companyUrn":"urn:li:fs_miniCompany:1586",
      "recommendations":[  

      ],
      "$type":"com.linkedin.voyager.identity.profile.Position"
   },
   {  
      "$deletedFields":[  
         "courses",
         "projects",
         "companyUrn",
         "honors",
         "entityLocale",
         "organizations",
         "company",
         "promotion"
      ],
      "locationName":"Brazil",
      "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295155453)",
      "companyName":"SuperUber (Rio de Janeiro), Conception (Rio de Janeiro), TIM (São Paulo), City of São Paulo",
      "timePeriod":{  
         "endDate":{  
            "month":3,
            "year":2016,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":3,
            "year":2008,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "description":"Conceived and developed a range of interactive installations using technologies including machine learning, computer vision, distributed computing and alternative controllers.\n\nFor ArtRio I developed an installation that let participants paint on a blank canvas using their voice and head movements with the help of camera tracking and a microphone. \nhttps://vimeo.com/77349535\n\nFor TIM mobile I developed an OpenGL based mountain climbing game in which a user used both hands with a pair of Wii controllers. In an installation for the world cup people were able to take a selfie with the official mascot being superimposed onto the image using image recognition and processing.\n\nFor superuber I developed interactive installations such as letting users draw in simulated sand, create a song with their silhouette from loops by dancing in front of a camera\n\ntech: javascript × groovy × java × actionscript × node.js × meteor × opengl ×  alternative controllers",
      "title":"Freelance Developer",
      "region":"urn:li:fs_region:(br,0)",
      "recommendations":[  

      ],
      "$type":"com.linkedin.voyager.identity.profile.Position"
   },
   {  
      "$deletedFields":[  
         "courses",
         "projects",
         "honors",
         "entityLocale",
         "organizations",
         "promotion"
      ],
      "locationName":"Portland, Oregon Area",
      "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295171529)",
      "companyName":"Sun Microsystems",
      "timePeriod":{  
         "endDate":{  
            "month":7,
            "year":2005,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":8,
            "year":2004,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "description":"Worked as a team developer on several inner process projects.\n\nResearched and developed a prototype failure analysis classification engine using technologies from the field of data mining and artificial intelligence.\n\nTech: java ×  spring framework ×  test driven development ×  agile development ×  python ×  distributed computing ",
      "company":{  
         "employeeCountRange":{  
            "start":10001,
            "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
         },
         "industries":[  
            "Information Technology and Services"
         ],
         "*miniCompany":"urn:li:fs_miniCompany:1062",
         "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
      },
      "title":"Software Engineer",
      "region":"urn:li:fs_region:(us,79)",
      "companyUrn":"urn:li:fs_miniCompany:1062",
      "recommendations":[  

      ],
      "$type":"com.linkedin.voyager.identity.profile.Position"
   },
   {  
      "$deletedFields":[  

      ],
      "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,8)",
      "timePeriod":{  
         "endDate":{  
            "month":7,
            "year":2005,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":8,
            "year":2004,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "name":"Sun Microsystems",
      "paging":{  
         "total":1,
         "start":0,
         "count":1,
         "links":[  

         ],
         "$type":"com.linkedin.restli.common.CollectionMetadata"
      },
      "*miniCompany":"urn:li:fs_miniCompany:1062",
      "*positions":[  
         "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295171529)"
      ],
      "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
   },
   {  
      "$deletedFields":[  
         "miniCompany"
      ],
      "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,9)",
      "timePeriod":{  
         "endDate":{  
            "month":1,
            "year":2005,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":1,
            "year":2003,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "name":"Edinburgh Pedicabs",
      "paging":{  
         "total":1,
         "start":0,
         "count":1,
         "links":[  

         ],
         "$type":"com.linkedin.restli.common.CollectionMetadata"
      },
      "*positions":[  
         "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295173992)"
      ],
      "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
   },
   {  
      "$deletedFields":[  

      ],
      "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,6)",
      "timePeriod":{  
         "endDate":{  
            "month":10,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":6,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "name":"The University of Edinburgh",
      "paging":{  
         "total":1,
         "start":0,
         "count":1,
         "links":[  

         ],
         "$type":"com.linkedin.restli.common.CollectionMetadata"
      },
      "*miniCompany":"urn:li:fs_miniCompany:5738",
      "*positions":[  
         "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,47250208)"
      ],
      "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
   },
   {  
      "$deletedFields":[  

      ],
      "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,7)",
      "timePeriod":{  
         "endDate":{  
            "month":2,
            "year":2007,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":10,
            "year":2006,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "name":"Amazon",
      "paging":{  
         "total":1,
         "start":0,
         "count":1,
         "links":[  

         ],
         "$type":"com.linkedin.restli.common.CollectionMetadata"
      },
      "*miniCompany":"urn:li:fs_miniCompany:1586",
      "*positions":[  
         "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295173319)"
      ],
      "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
   },
   {  
      "$deletedFields":[  
         "miniCompany"
      ],
      "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,5)",
      "timePeriod":{  
         "endDate":{  
            "month":3,
            "year":2016,
            "$type":"com.linkedin.common.Date"
         },
         "startDate":{  
            "month":3,
            "year":2008,
            "$type":"com.linkedin.common.Date"
         },
         "$type":"com.linkedin.voyager.common.DateRange"
      },
      "name":"SuperUber (Rio de Janeiro), Conception (Rio de Janeiro), TIM (São Paulo), City of São Paulo",
      "paging":{  
         "total":1,
         "start":0,
         "count":1,
         "links":[  

         ],
         "$type":"com.linkedin.restli.common.CollectionMetadata"
      },
      "*positions":[  
         "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295155453)"
      ],
      "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
   },
     {
        "$deletedFields":[
           "universalName"
        ],
        "objectUrn":"urn:li:company:2801128",
        "entityUrn":"urn:li:fs_miniCompany:2801128",
        "name":"Envisioning",
        "showcase":false,
        "active":true,
        "logo":{
           "artifacts":[
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=83Oz0ZisfjkCLARqq9zfDhMFHllRomiJZpOns-veeC0",
                 "expiresAt":1557964800000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=4YXaW6vDEHJnTrZXD-J9vMX2mN2ZYfPJGFOhLzne6Xk",
                 "expiresAt":1557964800000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=DlkEIDPuTjXHvbdlI6HVnJeZkcd0HAYVYYIAiLsAKL8",
                 "expiresAt":1557964800000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4E0BAQGWJOKWa0OIAg/company-logo_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "trackingId":"mB6euGzLTDKeZWRcVAIImw==",
        "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
     },
     {
        "$deletedFields":[
           "universalName"
        ],
        "objectUrn":"urn:li:company:655921",
        "entityUrn":"urn:li:fs_miniCompany:655921",
        "name":"MUTEK",
        "showcase":false,
        "active":true,
        "logo":{
           "artifacts":[
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=lUc81-09cKsY_jifYv-65cM3y48BySE7vtl1z5fx_oE",
                 "expiresAt":1557964800000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=GC6B3FP51rmCgxByTham-f0MOQ2_OqRucpuP64zDaCI",
                 "expiresAt":1557964800000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=E25RdGGy7t7PVUlM6h9sEGT7ZlvtMg7ujYA0tF5ZlZY",
                 "expiresAt":1557964800000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4E0BAQE99JP34J_SPw/company-logo_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "trackingId":"QOpNAYLXSrKS2TjkEFzFAg==",
        "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
     },
     {
        "$deletedFields":[
           "universalName"
        ],
        "objectUrn":"urn:li:company:1274501",
        "entityUrn":"urn:li:fs_miniCompany:1274501",
        "name":"transmediale - art & digital culture",
        "showcase":false,
        "active":true,
        "logo":{
           "artifacts":[
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=L2g-B64oMlproqqKB4_S_ECsgcxcUqaC9SjSyVSj8U0",
                 "expiresAt":1557964800000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=wvNFmKt3diD558ck88DgjIbOsg0PjZSrOHFoqo53Yeg",
                 "expiresAt":1557964800000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=wB-K5AzB7Cq_BNb-9iSXh-Qii5XBdXEbQJc3URxSZ9g",
                 "expiresAt":1557964800000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4E0BAQG_BhYfWKewAA/company-logo_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "trackingId":"yhtrKtUrRpeBJL2Ab36BVA==",
        "$type":"com.linkedin.voyager.entities.shared.MiniCompany"
     },
     {
        "$deletedFields":[

        ],
        "objectUrn":"urn:li:school:12665",
        "entityUrn":"urn:li:fs_miniSchool:12665",
        "active":true,
        "logo":{
           "artifacts":[
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1557964800&v=beta&t=Sl3kEyzyO9ef0sqZtOEyca_hAZ2lZx7K8uXifwJqe54",
                 "expiresAt":1557964800000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1557964800&v=beta&t=UtjjKjm9auHnM_fBakNlp59OZmWCr3HPRAmenEw0lMQ",
                 "expiresAt":1557964800000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1557964800&v=beta&t=8l2mSYVK7M7c3hwxxdyTosxctjG0VQOBGHAP5oxgSLc",
                 "expiresAt":1557964800000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4D0BAQFSi1nlisxTcg/company-logo_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "schoolName":"The University of Edinburgh",
        "trackingId":"bfDQc0ZeT8GeC80rLw5SXg==",
        "$type":"com.linkedin.voyager.entities.shared.MiniSchool"
     },
     {
        "$deletedFields":[
           "objectUrn",
           "trackingId"
        ],
        "entityUrn":"urn:li:fs_miniSkill:698",
        "name":"Programming",
        "$type":"com.linkedin.voyager.entities.shared.MiniSkill"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_certificationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.CertificationView"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35961977,178532175)",
        "*member":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215652152)",
        "name":"Barbara Webb",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35792367,178590889)",
        "*member":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653256)",
        "*member":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651739)",
        "name":"Ho Duc Thang",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651740)",
        "name":"Chin Hiong Tan",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653072)",
        "name":"Tomoharu Nakashima",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215651736)",
        "name":"Markos Zampoglou",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653258)",
        "name":"Barbara Webb",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215649780)",
        "name":"Jonathan M. Garibaldi",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215653066)",
        "name":"Hugo Rosano",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215652249)",
        "name":"Michael Mangan",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653071)",
        "name":"Julian Togelius",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215651735)",
        "*member":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215652153)",
        "name":"Jan Wessnitzer",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653257)",
        "*member":"urn:li:fs_miniProfile:ACoAAADS77IB2mM5SKB0MHXF1hx0fjmHZmdYO2o",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAADS77IB2mM5SKB0MHXF1hx0fjmHZmdYO2o",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651738)",
        "name":"Simon M. Lucas",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "member",
           "profileUrn"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215653067)",
        "name":"Matthew Szenher",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[
           "name"
        ],
        "entityUrn":"urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653070)",
        "*member":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "$type":"com.linkedin.voyager.identity.profile.Contributor"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_courseView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.CourseView"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "recommendations",
           "honors",
           "entityLocale",
           "activities",
           "fieldOfStudyUrn",
           "testScores"
        ],
        "entityUrn":"urn:li:fs_education:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,527355838)",
        "grade":"First-class honors",
        "timePeriod":{
           "endDate":{
              "year":2006,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "year":2001,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Modules: Artificial Intelligence, Computer Science, Mathematics, Physics, Advanced Vision, Computational Complexity, Intelligent Autonomous Robotics, Modelling and Simulation, Visualization, Neural Computation\n\nExtra: French, Human Communication",
        "*school":"urn:li:fs_miniSchool:12665",
        "degreeName":"Bachelor of Science - BS",
        "schoolName":"The University of Edinburgh",
        "fieldOfStudy":"Artificial Intelligence and Computer Science",
        "degreeUrn":"urn:li:fs_degree:400",
        "schoolUrn":"urn:li:fs_miniSchool:12665",
        "$type":"com.linkedin.voyager.identity.profile.Education"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "recommendations",
           "honors",
           "schoolUrn",
           "entityLocale",
           "school",
           "activities",
           "fieldOfStudyUrn",
           "testScores",
           "fieldOfStudy",
           "degreeUrn"
        ],
        "entityUrn":"urn:li:fs_education:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,577263475)",
        "grade":"grade: 1.7",
        "timePeriod":{
           "endDate":{
              "year":2001,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "year":1995,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Main subjects: Mathematics, Physics, History, English \nSubsidiary subjects: Philosophy, Informatics, Social Science, Music\n\nAwarded honorary membership of the German Physics Society",
        "degreeName":"Abitur",
        "schoolName":"Albert­ Schweitzer­ Gymnasium, Kassel",
        "$type":"com.linkedin.voyager.identity.profile.Education"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_educationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":2,
           "start":0,
           "count":3,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_education:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,527355838)",
           "urn:li:fs_education:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,577263475)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.EducationView"
     },
     {
        "$deletedFields":[
           "occupation"
        ],
        "entityUrn":"urn:li:fs_honor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,39047288)",
        "description":"Trained a neural network based agent to compete successfully in an online car racing competition.",
        "title":"The 2007 IEEE CEC Simulated Car Racing Competition (2nd Place)",
        "issueDate":{
           "month":6,
           "year":2007,
           "$type":"com.linkedin.common.Date"
        },
        "issuer":"IEEE Congress on Evolutionary Computation",
        "$type":"com.linkedin.voyager.identity.profile.Honor"
     },
     {
        "$deletedFields":[
           "occupation",
           "description"
        ],
        "entityUrn":"urn:li:fs_honor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38956486)",
        "title":"Honorary Membership",
        "issueDate":{
           "month":5,
           "year":2001,
           "$type":"com.linkedin.common.Date"
        },
        "issuer":"German Physics Society",
        "$type":"com.linkedin.voyager.identity.profile.Honor"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_honorView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":2,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_honor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,39047288)",
           "urn:li:fs_honor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38956486)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.HonorView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35226986)",
        "name":"English",
        "proficiency":"NATIVE_OR_BILINGUAL",
        "$type":"com.linkedin.voyager.identity.profile.Language"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35209111)",
        "name":"Portuguese",
        "proficiency":"FULL_PROFESSIONAL",
        "$type":"com.linkedin.voyager.identity.profile.Language"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35256919)",
        "name":"French",
        "proficiency":"LIMITED_WORKING",
        "$type":"com.linkedin.voyager.identity.profile.Language"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35240546)",
        "name":"German",
        "proficiency":"NATIVE_OR_BILINGUAL",
        "$type":"com.linkedin.voyager.identity.profile.Language"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_languageView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":4,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35226986)",
           "urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35256919)",
           "urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35240546)",
           "urn:li:fs_language:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35209111)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.LanguageView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_organizationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.OrganizationView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_patentView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.PatentView"
     },
     {
        "$deletedFields":[
           "courses",
           "entityLocale",
           "organizations",
           "company",
           "companyUrn",
           "recommendations",
           "honors",
           "promotion"
        ],
        "locationName":"São Paulo Area, Brazil",
        "projects":[
           "urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35792367)",
           "urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35961977)"
        ],
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295141594)",
        "companyName":"Voodoohop",
        "timePeriod":{
           "endDate":{
              "month":12,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":1,
              "year":2010,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"As one of the founders of the multidisciplinary art collective Voodoohop, I became deeply involved with the art and music scene of São Paulo and Brazil. Guided by a hedonistic attitude that stimulates individual and joint freedom of expression, Voodoohop is enjoying international success with performances at events all over Europe, the USA, South America and a sold out physical release in Japan.\n\nAs a musician I perform live, mixing South American elements with contemporary electronica. I have created a unique live performance in which Software I developed is responsible for generating harmony, melody and modifying the musical arrangements in real time.",
        "title":"Artist and Organizer",
        "region":"urn:li:fs_region:(br,6368)",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "entityLocale",
           "organizations",
           "recommendations",
           "honors",
           "promotion"
        ],
        "locationName":"Berlin Area, Germany",
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385971595)",
        "companyName":"Envisioning",
        "timePeriod":{
           "endDate":{
              "month":11,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":9,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Researched future trends of Artificial Intelligence for the World Government Summit in Dubai.",
        "company":{
           "employeeCountRange":{
              "start":11,
              "end":50,
              "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
           },
           "industries":[
              "Research"
           ],
           "*miniCompany":"urn:li:fs_miniCompany:2801128",
           "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
        },
        "title":"Foresight Researcher",
        "region":"urn:li:fs_region:(de,4944)",
        "companyUrn":"urn:li:fs_miniCompany:2801128",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "companyUrn",
           "recommendations",
           "honors",
           "entityLocale",
           "organizations",
           "company",
           "promotion"
        ],
        "locationName":"São Paulo Area, Brazil",
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295169201)",
        "companyName":"Secretaria da Cultura",
        "timePeriod":{
           "endDate":{
              "month":6,
              "year":2016,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":6,
              "year":2013,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Worked as a curator at the Virada Cultural, one of the world's biggest free street festivals. I was involved in the creation of a culture of free events in the center of São Paulo. Additionally curated and produced an annual free street party called \"SP Na Rua\" which showcases São Paulo's alternative art collectives.\n",
        "title":"Curator and Event Production",
        "region":"urn:li:fs_region:(br,6368)",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "entityLocale",
           "organizations",
           "recommendations",
           "honors",
           "promotion"
        ],
        "locationName":"Montreal, Canada Area",
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1348054231)",
        "companyName":"MUTEK",
        "timePeriod":{
           "endDate":{
              "month":6,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":5,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Conceived the live visuals for the band \"Die Wilde Jagd\" by creating a system that visualizes audio using Deep Neural Networks. Subsequently got  invited to give a talk on applications of AI with art at the Frontiere IA conference in Montreal",
        "company":{
           "employeeCountRange":{
              "start":11,
              "end":50,
              "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
           },
           "industries":[
              "Music"
           ],
           "*miniCompany":"urn:li:fs_miniCompany:655921",
           "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
        },
        "title":"Talk about Artificial Intelligence and Art at the Frontiere IA Conference",
        "region":"urn:li:fs_region:(ca,4863)",
        "companyUrn":"urn:li:fs_miniCompany:655921",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "entityLocale",
           "organizations",
           "recommendations",
           "honors",
           "promotion"
        ],
        "locationName":"Berlin Area, Germany",
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295163921)",
        "companyName":"transmediale - art & digital culture",
        "timePeriod":{
           "endDate":{
              "month":3,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":3,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Conceived and performed a musical piece which used the smartphones of the attendees to listen and react by generating sounds. This resulted in a form of musical swarm intelligence which blurs the border between performer and participant.\n\nhttp://www.ctm-festival.de/festival-2018/transfer/musicmakers-hacklab/",
        "company":{
           "employeeCountRange":{
              "start":2,
              "end":10,
              "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
           },
           "industries":[
              "Museums and Institutions"
           ],
           "*miniCompany":"urn:li:fs_miniCompany:1274501",
           "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
        },
        "title":"Machine Learning and Music  - Limited Contract Project",
        "region":"urn:li:fs_region:(de,4944)",
        "companyUrn":"urn:li:fs_miniCompany:1274501",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "courses",
           "projects",
           "entityLocale",
           "organizations",
           "recommendations",
           "honors",
           "promotion"
        ],
        "locationName":"Berlin Area, Germany",
        "entityUrn":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385968811)",
        "companyName":"Envisioning",
        "timePeriod":{
           "startDate":{
              "month":9,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Currently researching technologies that will impact sustainability in the medium- and long-term future for the GIZ (Deutsche Gesellschaft fuer Internationale Zusammenarbeit) in Germany.",
        "company":{
           "employeeCountRange":{
              "start":11,
              "end":50,
              "$type":"com.linkedin.voyager.identity.profile.EmployeeCountRange"
           },
           "industries":[
              "Research"
           ],
           "*miniCompany":"urn:li:fs_miniCompany:2801128",
           "$type":"com.linkedin.voyager.identity.profile.PositionCompany"
        },
        "title":"Foresight Researcher",
        "region":"urn:li:fs_region:(de,4944)",
        "companyUrn":"urn:li:fs_miniCompany:2801128",
        "$type":"com.linkedin.voyager.identity.profile.Position"
     },
     {
        "$deletedFields":[
           "miniCompany"
        ],
        "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1)",
        "timePeriod":{
           "endDate":{
              "month":12,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":1,
              "year":2010,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "name":"Voodoohop",
        "paging":{
           "total":1,
           "start":0,
           "count":2,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*positions":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295141594)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,2)",
        "timePeriod":{
           "endDate":{
              "month":6,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":5,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "name":"MUTEK",
        "paging":{
           "total":1,
           "start":0,
           "count":2,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*miniCompany":"urn:li:fs_miniCompany:655921",
        "*positions":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1348054231)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,3)",
        "timePeriod":{
           "endDate":{
              "month":3,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":3,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "name":"transmediale - art & digital culture",
        "paging":{
           "total":1,
           "start":0,
           "count":2,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*miniCompany":"urn:li:fs_miniCompany:1274501",
        "*positions":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295163921)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,0)",
        "timePeriod":{
           "startDate":{
              "month":9,
              "year":2018,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "name":"Envisioning",
        "paging":{
           "total":2,
           "start":0,
           "count":5,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*miniCompany":"urn:li:fs_miniCompany:2801128",
        "*positions":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385968811)",
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385971595)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
     },
     {
        "$deletedFields":[
           "miniCompany"
        ],
        "entityUrn":"urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,4)",
        "timePeriod":{
           "endDate":{
              "month":6,
              "year":2016,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":6,
              "year":2013,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "name":"Secretaria da Cultura",
        "paging":{
           "total":1,
           "start":0,
           "count":2,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*positions":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295169201)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroup"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_positionGroupView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":12,
           "start":0,
           "count":5,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,0)",
           "urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1)",
           "urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,2)",
           "urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,3)",
           "urn:li:fs_positionGroup:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,4)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionGroupView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_positionView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":13,
           "start":0,
           "count":5,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385968811)",
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295141594)",
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1385971595)",
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1348054231)",
           "urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295163921)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PositionView"
     },
     {
        "summary":"After studying Computer Science & Artificial Intelligence at Edinburgh University, I spent 9 years in São Paulo creating an art collective that mixes alternative art and technology. Always keeping one foot in the technology sector, I conceived and implemented a variety of interactive installations, combining my passion for art, research, and technology.\n\nAfter settling back in Germany and I shifted my focus to research and technology again and recently completed a project which involved researching the future trends of Artificial Intelligence for the World Government summit in Dubai.  Having interned at Sun Microsystems and worked at Amazon after University, I have a strong background in Java and agile development practices. More recently, I have created artistic experiences involving a variety of technologies, including Node.js, Functional Reactive Programming, Python, machine learning, intelligent sensors, data visualization, distributed computing, physics engines, and spatialized sound. \n",
        "industryName":"Information Technology & Services",
        "lastName":"Haferlach",
        "supportedLocales":[
           {
              "country":"US",
              "language":"en",
              "$type":"com.linkedin.common.Locale"
           }
        ],
        "locationName":"Berlin, Berlin, Germany",
        "student":false,
        "*miniProfile":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "versionTag":"3037008369",
        "elt":false,
        "profilePictureOriginalImage":{
           "artifacts":[
              {
                 "width":800,
                 "fileIdentifyingUrlPathSegment":"900_1200/0?m=AQJLP9wxIVBsdgAAAWjdu56MfU6NTeBRxTiyr8yOFQcND7E3si1Tw12S&e=1549994687&v=beta&t=CxBa88fQ-rPZQN-2S8rLdy25OHkQSKKYI0ehThkvq64",
                 "expiresAt":1549994687000,
                 "height":900,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"450_600/0?m=AQLDBLz54B2fOwAAAWjdu56Marm7zqyvqLs4PA-IjO6qrmzgleDWR68r&e=1549994687&v=beta&t=ddu_EiPQPw-VcwhQbV2T_SG7OoEm5Pi_oRSKsdCIroo",
                 "expiresAt":1549994687000,
                 "height":450,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://www.linkedin.com/dms/C4E04AQHKJjl5hqHChA/profile-originalphoto-shrink_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "birthDate":{
           "month":6,
           "day":4,
           "$type":"com.linkedin.common.Date"
        },
        "industryUrn":"urn:li:fs_industry:96",
        "$type":"com.linkedin.voyager.identity.profile.Profile",
        "defaultLocale":{
           "country":"US",
           "language":"en",
           "$type":"com.linkedin.common.Locale"
        },
        "firstName":"Thomas",
        "profilePicture":{
           "displayImage":"urn:li:digitalmediaAsset:C4E03AQEmUSb1fuhAiw",
           "originalImage":"urn:li:digitalmediaAsset:C4E04AQHKJjl5hqHChA",
           "photoFilterEditInfo":{
              "bottomLeft":{
                 "x":-6.178632484870436E-17,
                 "y":0.9327740355174525,
                 "$type":"com.linkedin.common.Coordinate2D"
              },
              "saturation":0.0,
              "brightness":0.0,
              "vignette":0.0,
              "photoFilterType":"ORIGINAL",
              "bottomRight":{
                 "x":1.0,
                 "y":0.9327740355174525,
                 "$type":"com.linkedin.common.Coordinate2D"
              },
              "topLeft":{
                 "x":-6.178632484870436E-17,
                 "y":0.04404164115125542,
                 "$type":"com.linkedin.common.Coordinate2D"
              },
              "contrast":0.0,
              "topRight":{
                 "x":1.0,
                 "y":0.04404164115125542,
                 "$type":"com.linkedin.common.Coordinate2D"
              },
              "$type":"com.linkedin.voyager.identity.profile.PhotoFilterEditInfo"
           },
           "$type":"com.linkedin.voyager.identity.profile.PhotoFilterPicture"
        },
        "$deletedFields":[
           "backgroundImage",
           "maidenName",
           "phoneticLastName",
           "entityLocale",
           "state",
           "phoneticFirstName",
           "address",
           "pictureInfo",
           "backgroundPicture",
           "backgroundPictureOriginalImage"
        ],
        "showEducationOnProfileTopCard":true,
        "entityUrn":"urn:li:fs_profile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "location":{
           "basicLocation":{
              "countryCode":"de",
              "postalCode":"12045",
              "$type":"com.linkedin.voyager.common.NormBasicLocation"
           },
           "preferredGeoPlace":"urn:li:fs_city:(de,2-1)",
           "$type":"com.linkedin.voyager.identity.profile.ProfileLocation"
        },
        "headline":"Machine Learning, Interactive Installations, Computer Science, Event Production, Audio/visual"
     },
     {
        "$deletedFields":[

        ],
        "occupation":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295141594)",
        "entityUrn":"urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35961977)",
        "timePeriod":{
           "startDate":{
              "month":2,
              "year":2010,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"Conceived and implemented social media campaigns for Voodoohop resulting in a vibrant online community with over 60000 followers",
        "title":"Voodoohop Social Media Strategy",
        "url":"http://facebook.com/voodoohop",
        "$type":"com.linkedin.voyager.identity.profile.Project",
        "*members":[
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35961977,178532175)"
        ]
     },
     {
        "$deletedFields":[

        ],
        "occupation":"urn:li:fs_position:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1295141594)",
        "entityUrn":"urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35792367)",
        "timePeriod":{
           "endDate":{
              "month":1,
              "year":2017,
              "$type":"com.linkedin.common.Date"
           },
           "startDate":{
              "month":1,
              "year":2016,
              "$type":"com.linkedin.common.Date"
           },
           "$type":"com.linkedin.voyager.common.DateRange"
        },
        "description":"An innovative way of visualizing musical harmony using colors, waveforms and the harmonic circle. \n\ntech: react - max/msp - ableton live - electron - node.js",
        "title":"Harmonic Audio Mixing Visualization Tools",
        "url":"https://github.com/voodoohop/voodoohop-ableton-tools/",
        "$type":"com.linkedin.voyager.identity.profile.Project",
        "*members":[
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35792367,178590889)"
        ]
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_projectView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":2,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35961977)",
           "urn:li:fs_project:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,35792367)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.ProjectView"
     },
     {
        "date":{
           "month":1,
           "year":2009,
           "day":1,
           "$type":"com.linkedin.common.Date"
        },
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153)",
        "*authors":[
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215651735)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215652152)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215652153)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215653066)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215653067)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153,215651736)"
        ],
        "name":"Low Level Approaches to Cognitive Control",
        "publisher":"Spatial Temporal Patterns for Action-Oriented Perception in Roving Robots",
        "description":"We describe several neural network implementions of insect based methods of navigation. We present the preliminary results of modelling associative learning capabilities based on the insect mushroom bodies.",
        "url":"https://www.researchgate.net/publication/251147936_Low_Level_Approaches_to_Cognitive_Control",
        "$type":"com.linkedin.voyager.identity.profile.Publication"
     },
     {
        "date":{
           "month":3,
           "year":2008,
           "day":1,
           "$type":"com.linkedin.common.Date"
        },
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841)",
        "*authors":[
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653070)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653071)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651738)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651739)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215649780)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215653072)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841,215651740)"
        ],
        "name":"The 2007 IEEE CEC simulated car racing competition",
        "publisher":"Genetic Programming and Evolvable Machines",
        "description":"With this paper, we hope to provide some insight into the efficacy of various computational intelligence methods on a well-defined game task, as well as an example of one way of running a competition. In the process, we provide a set of reference results for those who wish to use the simplerace game to benchmark their own algorithms. \n",
        "url":"https://link.springer.com/article/10.1007/s10710-008-9063-0",
        "$type":"com.linkedin.voyager.identity.profile.Publication"
     },
     {
        "date":{
           "month":3,
           "year":2007,
           "day":1,
           "$type":"com.linkedin.common.Date"
        },
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874)",
        "*authors":[
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653256)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653257)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215653258)",
           "urn:li:fs_contributor:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874,215652249)"
        ],
        "name":"Evolving a Neural Model of Insect Path Integration",
        "publisher":"Adaptive Behaviour 15(3)",
        "description":"We use a genetic algorithm to evolve a novel neural model of path integration, based on input from cells that encode the heading of the agent in a manner comparable to the polarization-sensitive interneurons found in insects. The home vector is encoded across a circular array of cells that integrate this input. We demonstrate the capabilities of the network under noisy conditions in simulation and on a robot.",
        "url":"http://journals.sagepub.com/doi/abs/10.1177/1059712307082080",
        "$type":"com.linkedin.voyager.identity.profile.Publication"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_publicationView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":3,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875484153)",
           "urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,875296841)",
           "urn:li:fs_publication:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,38442874)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.PublicationView"
     },
     {
        "*standardizedSkill":"urn:li:fs_miniSkill:698",
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1)",
        "standardizedSkillUrn":"urn:li:fs_miniSkill:698",
        "name":"Programming",
        "$type":"com.linkedin.voyager.identity.profile.Skill"
     },
     {
        "$deletedFields":[
           "standardizedSkillUrn",
           "standardizedSkill"
        ],
        "entityUrn":"urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,2)",
        "name":"Machine Learning",
        "$type":"com.linkedin.voyager.identity.profile.Skill"
     },
     {
        "$deletedFields":[
           "standardizedSkillUrn",
           "standardizedSkill"
        ],
        "entityUrn":"urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,3)",
        "name":"Functional Programming",
        "$type":"com.linkedin.voyager.identity.profile.Skill"
     },
     {
        "$deletedFields":[
           "standardizedSkillUrn",
           "standardizedSkill"
        ],
        "entityUrn":"urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,4)",
        "name":"Distributed Computing",
        "$type":"com.linkedin.voyager.identity.profile.Skill"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_skillView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "paging":{
           "total":18,
           "start":0,
           "count":4,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "*elements":[
           "urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1)",
           "urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,2)",
           "urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,3)",
           "urn:li:fs_skill:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,4)"
        ],
        "$type":"com.linkedin.voyager.identity.profile.SkillView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_testScoreView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":10,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.TestScoreView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_volunteerCauseView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":0,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.VolunteerCauseView"
     },
     {
        "$deletedFields":[

        ],
        "entityUrn":"urn:li:fs_volunteerExperienceView:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "profileId":"ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "elements":[

        ],
        "paging":{
           "total":0,
           "start":0,
           "count":3,
           "links":[

           ],
           "$type":"com.linkedin.restli.common.CollectionMetadata"
        },
        "$type":"com.linkedin.voyager.identity.profile.VolunteerExperienceView"
     },
     {
        "$deletedFields":[
           "providerName"
        ],
        "data":{
           "previewImages":[
              {
                 "originalHeight":960,
                 "url":"https://media.licdn.com/media-proxy/ext?w=720&h=960&f=n&hash=kNS1LX8aGDAz0ONK9bIJy8R5fx0%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta9Er0UK-kg8TwU1v87-UrF2191dGRoeSAW_8RGbuq5HZM2jscZOOLbqorQgTcH8Hkg1mLOv9Qzm1FpGjb5XqLth43ZHjIsOwPlRQP01m1zEc6oJpb0lr5MHyXbilMX4WgL8IO2DsY-q-MQttWhpirrXbddeBcQtDiALcHIneTZwTDuYwoNgDkgkA9ZiSRJNtnLNkhmJ5zwG686v3NyxRusD7W1g",
                 "originalWidth":720,
                 "$type":"com.linkedin.voyager.common.MediaProxyImage"
              }
           ],
           "url":"http://voodoohop.com/thomash",
           "$type":"com.linkedin.voyager.identity.profile.treasury.Link"
        },
        "entityUrn":"urn:li:fs_treasuryMedia:(ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M,1549210628533)",
        "customDescription":"As one of the founders of the multidisciplinary art collective Voodoohop, Thomash became deeply involved with the art and music scene of São Paulo, Brazil and over the years, all over the world.",
        "description":"As one of the founders of the multidisciplinary art collective Voodoohop, Thomash became deeply involved with the art and music scene of São Paulo, Brazil and over the years, all over the world. South american elements mixed with contemporary...",
        "customTitle":"Thomash — VOODOOHOP",
        "title":"Thomash — VOODOOHOP",
        "$type":"com.linkedin.voyager.identity.profile.treasury.TreasuryMedia"
     },
     {
        "firstName":"Jan",
        "lastName":"Wessnitzer",
        "$deletedFields":[
           "backgroundImage"
        ],
        "occupation":"Co-Founder at Machines With Vision",
        "objectUrn":"urn:li:member:13823922",
        "entityUrn":"urn:li:fs_miniProfile:ACoAAADS77IB2mM5SKB0MHXF1hx0fjmHZmdYO2o",
        "publicIdentifier":"janwessnitzer",
        "picture":{
           "artifacts":[
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1555545600&v=beta&t=0rT2nYdf6LA4bmGC7ufd8NozAkp6oTpGuXG30KYPJ4I",
                 "expiresAt":1555545600000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1555545600&v=beta&t=F5uRG1eF5GzqhUtA_ttRXjPeF4vmHcF3HHXsSaOhFZ0",
                 "expiresAt":1555545600000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1555545600&v=beta&t=JtcAk9F0-W8X-uN75ZJd58sdrKRYeIbkda6kqP1rGNU",
                 "expiresAt":1555545600000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":800,
                 "fileIdentifyingUrlPathSegment":"800_800/0?e=1555545600&v=beta&t=KlfXiwedW_dE8Ybh4vkr7yLRfi1WqprHy0w0PfveBDU",
                 "expiresAt":1555545600000,
                 "height":800,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4E03AQHhfYBx8bEhfg/profile-displayphoto-shrink_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "trackingId":"NdVNxX+RSEKte3/9WECxig==",
        "$type":"com.linkedin.voyager.identity.shared.MiniProfile"
     },
     {
        "firstName":"Thomas",
        "lastName":"Haferlach",
        "$deletedFields":[
           "backgroundImage"
        ],
        "occupation":"Machine Learning, Interactive Installations, Computer Science, Event Production, Audio/visual",
        "objectUrn":"urn:li:member:29796967",
        "entityUrn":"urn:li:fs_miniProfile:ACoAAAHGqmcBmBX8XibDdMoWrh3wc4SWt8cDJ0M",
        "publicIdentifier":"thomashaferlach",
        "picture":{
           "artifacts":[
              {
                 "width":100,
                 "fileIdentifyingUrlPathSegment":"100_100/0?e=1555545600&v=beta&t=2Ph1AAhHlCNldW5Q9M1LRQixJoapxLdVbWYecxvjMpg",
                 "expiresAt":1555545600000,
                 "height":100,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":200,
                 "fileIdentifyingUrlPathSegment":"200_200/0?e=1555545600&v=beta&t=Rhmt8MEIoESFNQvH2TdE9zYFLeTDQSv7k-w1x2bZOyI",
                 "expiresAt":1555545600000,
                 "height":200,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":400,
                 "fileIdentifyingUrlPathSegment":"400_400/0?e=1555545600&v=beta&t=Xn1VUMhonY5G1nuQQ2_8liIk-RH1RMa4E6_C2M2zFtc",
                 "expiresAt":1555545600000,
                 "height":400,
                 "$type":"com.linkedin.common.VectorArtifact"
              },
              {
                 "width":800,
                 "fileIdentifyingUrlPathSegment":"800_800/0?e=1555545600&v=beta&t=i2r_-k9_xxvtnw0mAUEdtnKnSU9a5HM908xcthSJSQo",
                 "expiresAt":1555545600000,
                 "height":800,
                 "$type":"com.linkedin.common.VectorArtifact"
              }
           ],
           "rootUrl":"https://media.licdn.com/dms/image/C4E03AQEmUSb1fuhAiw/profile-displayphoto-shrink_",
           "$type":"com.linkedin.common.VectorImage"
        },
        "trackingId":"2Q8GU0kuSl67tZ1Y/Vow0A==",
        "$type":"com.linkedin.voyager.identity.shared.MiniProfile"
     }
  ]
}